"""P5-A: Aside browser semantic contract tests.

Asserts that captured evidence artifacts from the 7 semantic journeys
exist and match the contract. The evidence is generated by
scripts/gen_aside_evidence.py and stored under
evidence/ontology-platform-roadmap/task-10-*.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = str(Path(__file__).resolve().parent.parent)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import pytest  # noqa: E402

EVIDENCE = Path(_ROOT) / "evidence" / "ontology-platform-roadmap"


def _load(name: str) -> dict:
    path = EVIDENCE / f"task-10-{name}"
    assert path.exists(), f"evidence artifact missing: {path}"
    return json.loads(path.read_text())


def _load_text(name: str) -> str:
    path = EVIDENCE / f"task-10-{name}"
    assert path.exists(), f"evidence artifact missing: {path}"
    return path.read_text()


class TestAsideSemanticContract:
    """Contract assertions from the 7 semantic journey evidence."""

    def test_summary_all_pass(self):
        summary = _load("summary.json")
        assert summary["all_pass"] is True
        for journey, passed in summary["journeys"].items():
            assert passed, f"journey {journey} failed"

    def test_j1_schema_meaning(self):
        schema = _load("j1-schema.json")
        active = schema.get("active", {})
        assert len(active.get("entity_types", [])) > 0
        assert len(active.get("relation_types", [])) > 0
        result = _load_text("j1-result.txt")
        assert "PASS=True" in result

    def test_j2_identity_conflict(self):
        entities = _load("j2-entities.json")
        items = entities.get("items", [])
        assert len(items) > 0
        for item in items:
            assert item.get("id"), f"item missing id: {item}"
        result = _load_text("j2-result.txt")
        assert "PASS=True" in result

    def test_j3_qualifier_evidence(self):
        proposals = _load("j3-proposals.json")
        edges = [r for r in proposals.get("items", []) if r.get("kind") == "edge"]
        for e in edges:
            assert e.get("source_doc_id") or e.get("doc_title")
        result = _load_text("j3-result.txt")
        assert "PASS=True" in result

    def test_j4_asserted_proposed(self):
        packs = _load("j4-packs.json")
        assert "competency" in packs
        comp = packs["competency"]
        assert comp["all_passed"] is True
        assert comp["total_count"] == 3
        result = _load_text("j4-result.txt")
        assert "PASS=True" in result

    def test_j5_pack_compare_reselect(self):
        diff = _load("j5-diff.json")
        assert "manifest_changes" in diff or "identical" in diff
        assert "pack_a" in diff
        assert "pack_b" in diff
        result = _load_text("j5-result.txt")
        assert "PASS=True" in result

    def test_j6_failure_retry(self):
        failure = _load("j6-failure.json")
        assert failure["status"] in (400, 404)
        result = _load_text("j6-result.txt")
        assert "PASS=True" in result
        assert "no_data_loss=True" in result

    def test_j7_pack_audit(self):
        audit = _load("j7-audit.json")
        assert len(audit) >= 2
        for entry in audit:
            assert entry["has_hash"], f"pack {entry['pack_id']} missing content_hash"
            assert entry["has_counts"], f"pack {entry['pack_id']} missing counts"
        result = _load_text("j7-result.txt")
        assert "PASS=True" in result

    def test_cleanup_receipt(self):
        receipt = _load_text("cleanup-receipt.txt")
        assert "removed=True" in receipt
        assert "no_qa_processes=0" in receipt

    def test_acceptance_doc_exists(self):
        doc = Path(_ROOT) / "docs" / "ASIDE-ONTOLOGY-ACCEPTANCE.md"
        assert doc.exists()
        content = doc.read_text()
        assert "PASS" in content
        for i in range(1, 8):
            assert f"Journey {i}" in content
