#!/bin/bash
# Build a double-clickable macOS .app that starts the ontologylab local
# dashboard and opens it in the browser — "click app -> local page".
#
#   ./launcher/build-macos-app.sh [--out DIR] [--port N] [--repo PATH]
#
# Defaults: installs to ~/Applications, port 8765, repo = this checkout.
# The built .app is machine-specific (absolute paths baked in) and is NOT
# committed — this script is the reproducible source. Re-run it after moving
# the repo or changing the port.
set -euo pipefail

# --- resolve this repo (the launcher lives in <repo>/launcher/) ------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$HOME/Applications"
PORT="8765"
APP_NAME="ontologylab"

while [ $# -gt 0 ]; do
  case "$1" in
    --out)  OUT="$2"; shift 2;;
    --port) PORT="$2"; shift 2;;
    --repo) REPO="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

PY="$REPO/.venv/bin/python"
if [ ! -x "$PY" ]; then
  echo "error: venv python not found at $PY" >&2
  echo "create it first:  cd $REPO && python3.11 -m venv .venv && .venv/bin/pip install -e '.[server,mcp]'" >&2
  exit 1
fi

APP="$OUT/$APP_NAME.app"
CONTENTS="$APP/Contents"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

# --- Info.plist ------------------------------------------------------------
cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>ontologylab</string>
  <key>CFBundleIdentifier</key><string>town.neobio.ontologylab.launcher</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>ontologylab</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# --- launcher executable (baked with this repo + preferred port) -----------
cat > "$CONTENTS/MacOS/launch" <<LAUNCH
#!/bin/bash
# Auto-generated by launcher/build-macos-app.sh — do not edit; re-run the builder.
REPO="$REPO"
PY="$PY"
PREF_PORT="$PORT"
PORTFILE="\$REPO/.launcher.port"
LOG="\$REPO/.launcher.log"

# Is OUR dashboard already up on a given port? Distinguish from any other
# service on that port by hitting an ontologylab-specific JSON endpoint.
is_ours() {
  /usr/bin/curl -sf "http://127.0.0.1:\$1/api/engines" 2>/dev/null | /usr/bin/grep -q '"available"'
}
port_free() {
  ! /usr/sbin/lsof -iTCP:"\$1" -sTCP:LISTEN -n >/dev/null 2>&1
}

# 1) If a previous launch recorded a port and our server is still there, reuse.
if [ -f "\$PORTFILE" ]; then
  P="\$(cat "\$PORTFILE" 2>/dev/null)"
  if [ -n "\$P" ] && is_ours "\$P"; then
    /usr/bin/open "http://127.0.0.1:\$P/"; exit 0
  fi
fi

# 2) Pick a port: prefer the configured one, else scan upward for a free one
#    that no other service holds (Claude science, etc. often sit on 8765).
PORT=""
for CAND in \$PREF_PORT \$(seq \$((PREF_PORT+1)) \$((PREF_PORT+30))); do
  if is_ours "\$CAND"; then PORT="\$CAND"; break; fi   # already ours -> reuse
  if port_free "\$CAND"; then PORT="\$CAND"; break; fi
done
if [ -z "\$PORT" ]; then
  /usr/bin/osascript -e 'display alert "ontologylab" message "No free port near '"\$PREF_PORT"' — is something using them all?"' >/dev/null 2>&1
  exit 1
fi
URL="http://127.0.0.1:\$PORT/"

# 3) Already ours on the chosen port? just open it.
if is_ours "\$PORT"; then
  echo "\$PORT" > "\$PORTFILE"
  /usr/bin/open "\$URL"; exit 0
fi

# 4) Start the dashboard detached so it outlives this launcher process.
cd "\$REPO"
/usr/bin/nohup "\$PY" -m ontologylab.serve --port "\$PORT" > "\$LOG" 2>&1 &
disown 2>/dev/null || true
echo "\$PORT" > "\$PORTFILE"
for _ in \$(seq 1 60); do
  is_ours "\$PORT" && { /usr/bin/open "\$URL"; exit 0; }
  sleep 0.25
done
# startup slow/failed — open anyway so the user sees the state, and surface log
/usr/bin/open "\$URL"
exit 0
LAUNCH
chmod +x "$CONTENTS/MacOS/launch"

# --- companion "Stop" one-liner (Terminal) ---------------------------------
STOP="$OUT/Stop ontologylab.command"
cat > "$STOP" <<STOPSH
#!/bin/bash
pkill -f "ontologylab.serve --port" && echo "ontologylab stopped." || echo "ontologylab was not running."
rm -f "$REPO/.launcher.port"
sleep 1
STOPSH
chmod +x "$STOP"

# --- icon (generated; falls back silently if tools are unavailable) --------
if command -v sips >/dev/null && command -v iconutil >/dev/null; then
  TMP="$(mktemp -d)"
  ICONSET="$TMP/ontologylab.iconset"; mkdir -p "$ICONSET"
  # 1024px base PNG: dark ground + a green "verified node" glyph, drawn as a
  # tiny SVG rasterized by... we have no rasterizer, so build from a PPM.
  "$PY" - "$TMP/base.png" <<'PYICON' || true
import sys, struct, zlib, math
W = 1024
cx = cy = W/2
# palette: deep charcoal ground, fluorescein-green node, faint cyan ring
bg = (10, 16, 20)
green = (53, 230, 160)
cyan = (55, 210, 255)
def px(x, y):
    dx, dy = x-cx, y-cy
    d = math.hypot(dx, dy)
    # rounded-rect-ish vignette ground
    r = 150.0
    edge = max(abs(dx), abs(dy))
    if edge > W/2 - 40:
        return (0,0,0,0)  # transparent margin -> rounded by mask below
    # central node
    if d < 120:
        t = max(0.0, 1 - d/120)
        return (int(bg[0]+(green[0]-bg[0])*t),
                int(bg[1]+(green[1]-bg[1])*t),
                int(bg[2]+(green[2]-bg[2])*t), 255)
    # two orbit nodes (edges of a KG)
    for ox, oy, col in ((cx+260, cy-200, cyan), (cx-240, cy+230, green)):
        od = math.hypot(x-ox, y-oy)
        if od < 60:
            t = max(0.0, 1-od/60)
            return (int(bg[0]+(col[0]-bg[0])*t),
                    int(bg[1]+(col[1]-bg[1])*t),
                    int(bg[2]+(col[2]-bg[2])*t), 255)
    # faint green ring (fluorescence halo)
    if 150 < d < 158:
        return (green[0], green[1], green[2], 90)
    return (bg[0], bg[1], bg[2], 255)
# rounded corners mask
rad = 180
def rounded(x, y):
    for (qx, qy) in ((rad,rad),(W-rad,rad),(rad,W-rad),(W-rad,W-rad)):
        if (x<rad or x>W-rad) and (y<rad or y>W-rad):
            if math.hypot(x-qx, y-qy) > rad:
                return False
    return True
raw = bytearray()
for y in range(W):
    raw.append(0)
    for x in range(W):
        r,g,b,a = px(x,y)
        if not rounded(x,y):
            a = 0
        raw += bytes((r,g,b,a))
def chunk(tag, data):
    c = tag + data
    return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xffffffff)
png = b"\x89PNG\r\n\x1a\n"
png += chunk(b"IHDR", struct.pack(">IIBBBBB", W, W, 8, 6, 0, 0, 0))
png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
png += chunk(b"IEND", b"")
open(sys.argv[1], "wb").write(png)
PYICON
  if [ -f "$TMP/base.png" ]; then
    for s in 16 32 64 128 256 512 1024; do
      sips -z $s $s "$TMP/base.png" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null 2>&1 || true
    done
    # retina names
    cp "$ICONSET/icon_32x32.png"   "$ICONSET/icon_16x16@2x.png"   2>/dev/null || true
    cp "$ICONSET/icon_64x64.png"   "$ICONSET/icon_32x32@2x.png"   2>/dev/null || true
    cp "$ICONSET/icon_256x256.png" "$ICONSET/icon_128x128@2x.png" 2>/dev/null || true
    cp "$ICONSET/icon_512x512.png" "$ICONSET/icon_256x256@2x.png" 2>/dev/null || true
    cp "$ICONSET/icon_1024x1024.png" "$ICONSET/icon_512x512@2x.png" 2>/dev/null || true
    iconutil -c icns "$ICONSET" -o "$CONTENTS/Resources/ontologylab.icns" 2>/dev/null || true
  fi
  rm -rf "$TMP"
fi

# refresh Finder/Launchpad icon cache for this bundle
touch "$APP"

echo "Built: $APP"
echo "Stop helper: $STOP"
echo "Port: $PORT   Repo: $REPO"
echo
echo "Click '$APP_NAME' in ~/Applications (or Launchpad/Spotlight) to open the dashboard."
